{{- $top := $ }}  # Save the top-level context
{{- range $key, $secret := .Values.secretProviders }}
{{- if $secret.enabled }}

  {{- $secretNamespace := $top.Release.Namespace }}
  {{- $lookupData := (lookup "v1" "Secret" $secretNamespace $secret.name).data }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secret.name }}"
  namespace: {{ $secretNamespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: "{{ $secret.type }}"
data:
{{- if eq $secret.name "certificat-saml-sp" }}
  sp.key: |
{{ tpl $.Values.certificat.saml.sp.key_file $top | b64enc | nindent 4 }}
  sp.crt: |
{{ tpl $.Values.certificat.saml.sp.cert_file $top | b64enc | nindent 4 }}
  {{- else if eq $secret.type "Generated" }}
    {{- range $key := $secret.keys }}
    {{ $key }}: "{{ ((get $lookupData $key) | default (randAlphaNum 30 | b64enc)) }}"
    {{- end }}
  {{- else }}
    {{- range $key, $val := $secret.initialData }}
      {{- if eq $key "certificat.yml" }}
      {{ $key }}: "{{ tpl ($top.Files.Get "files/certificat.tpl.yml") $top | b64enc }}"
      {{- else }}
      {{ $key }}: "{{ ((get $lookupData $key) | default ($val | b64enc)) }}"
      {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
{{- end }}