{{- range $key, $secret := .Values.secretProviders }}
{{- if $secret.enabled }}

  {{- $secretNamespace := ($secret.namespace | default $.Values.namespace) }}  
  {{- $lookupData := (lookup "v1" "Secret" $secretNamespace $secret.name).data }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secret.name }}"  
  namespace: {{ $secretNamespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: "{{ $secret.type }}"
data:
  {{- if eq $secret.type "Generated" }}
    {{- range $key := $secret.keys }}
    {{ $key }}: "{{ ((get $lookupData $key) | default (randAlphaNum 30 | b64enc )) }}"  
    {{- end }}
  {{ else }}
    {{- range $key, $val := $secret.initialData }}  
    {{ $key }}: "{{ ((get $lookupData $key) | default ($val | b64enc )) }}"  
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
