{{- range $key, $secret := .Values.secretProviders }}
{{- if $secret.enabled }}
  {{- $secretNamespace := $.Release.Namespace }}
  {{- $lookupData := (lookup "v1" "Secret" $secretNamespace $secret.name).data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secret.name }}"
  namespace: {{ $secretNamespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: "{{ $secret.type }}"
data:
  {{- if eq $secret.type "Generated" }}
    {{- range $key := $secret.keys }}
    {{ $key }}: "{{ ((get $lookupData $key) | default (randAlphaNum 30 | b64enc )) }}"
    {{- end }}
  {{ else }}
    {{- range $dataKey, $dataVal := $secret.initialData }}
      {{- if and (eq $dataKey "certificat.yml") (eq $secret.name "certificat-file-secret") }}
    {{ $dataKey }}: >
      {{ tpl ($.Files.Get "files/certificat.tpl.yml") $ | b64enc }}
      {{- else }}
    {{ $dataKey }}: "{{ ((get $lookupData $dataKey) | default ($dataVal | b64enc )) }}"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
