certificat:
  url_root: "https://{{ .Values.ingress.hostname }}"
  login_method: {{ .Values.certificat.login_method | quote }}
  finalizer_module: "certificat.modules.acme.backends.local.LocalFinalizer"
  db:
    name: certificat
    user: certificat
    host: mariadb-service.{{ .Release.Namespace }}
  redis:
    host: redis-service.{{ .Release.Namespace }}

{{- if eq $.Values.certificat.login_method "saml" }}
saml:
  debug: {{ $.Values.certificat.saml.debug }}
  administrators:
    {{- $admins := split "," $.Values.certificat.saml.administrators }}
    {{- range $admins }}
    - "{{ . | trim }}"
    {{- end }}
  attribute_mapping:
    eduPersonPrincipalName: ["{{ $.Values.certificat.saml.attribute_mapping.eduPersonPrincipalName }}"]
    mail: ["{{ $.Values.certificat.saml.attribute_mapping.mail }}"]
    givenName: ["{{ $.Values.certificat.saml.attribute_mapping.givenName }}"]
    sn: ["{{ $.Values.certificat.saml.attribute_mapping.sn }}"]
  sp:
    entity_id: "{{ $.Values.certificat.saml.sp.entity_id }}"
    key_file: "{{ $.Values.certificat.saml.sp.key_file }}"
    cert_file: "{{ $.Values.certificat.saml.sp.cert_file }}"
  {{- if $.Values.certificat.saml.idp.remote_url }}
  idp:
    remote:
      - url: "{{ $.Values.certificat.saml.idp.remote_url }}"
  {{- else }}
  idp:
    mdq:
      - url: "http://mdq.incommon.org"
        cert: "/srv/www/config/inc-md-cert-mdq.pem"
        freshness_period: "P0Y0M0DT2H0M0S"
  {{- end }}
{{- end }}

{{- if or .Values.certificat.local_finalizer.key .Values.certificat.local_finalizer.cert }}
local_finalizer:
  key: |
    {{ .Values.certificat.local_finalizer.key | indent 4 }}
  cert: |
    {{ .Values.certificat.local_finalizer.cert | indent 4 }}
{{- end }}