certificat:
  url_root: "https://{{ .Values.ingress.hostname }}"
  login_method: {{ .Values.secretProviders.certificat.certificat.login_method | quote }}
  finalizer_module: "certificat.modules.acme.backends.local.LocalFinalizer"
  db:
    name: certificat
    user: certificat
    host: mariadb-service.{{ .Release.Namespace }}
  redis:
    host: redis-service.{{ .Release.Namespace }}

{{- if eq .Values.secretProviders.certificat.certificat.login_method "saml" }}
saml:
  debug: false
  attribute_mapping:
    eduPersonPrincipalName: ["username"]
    mail: ["email"]
    givenName: ["first_name"]
    sn: ["last_name"]
  sp:
    entity_id: "https://{{ .Values.ingress.hostname }}/saml2/metadata/"
    key_file: "/srv/www/config/sp.key"
    cert_file: "/srv/www/config/sp.crt"
  idp:
    mdq:
      - url: "http://mdq.incommon.org"
        cert: "/srv/www/config/inc-md-cert-mdq.pem"
        freshness_period: "P0Y0M0DT2H0M0S"
{{- end }}
