certificat:
  url_root: "https://{{ .Values.ingress.hostname }}"
  login_method: {{ .Values.certificat.login_method | quote }}
  finalizer_module: "certificat.modules.acme.backends.local.LocalFinalizer"
  db:
    name: certificat
    user: certificat
    host: mariadb-service.{{ .Release.Namespace }}
  redis:
    host: redis-service.{{ .Release.Namespace }}

{{- if eq $.Values.certificat.login_method "saml" }}
saml:
  debug: {{ $.Values.certificat.saml.debug }}
  administrators:
    {{- $admins := split "," $.Values.certificat.saml.administrators }}
    {{- range $admins }}
    - "{{ . | trim }}"
    {{- end }}
  attribute_mapping:
    eduPersonPrincipalName: ["{{ $.Values.certificat.saml.attribute_mapping.eduPersonPrincipalName }}"]
    mail: ["{{ $.Values.certificat.saml.attribute_mapping.mail }}"]
    givenName: ["{{ $.Values.certificat.saml.attribute_mapping.givenName }}"]
    sn: ["{{ $.Values.certificat.saml.attribute_mapping.sn }}"]
  sp:
    entity_id: "{{ $.Values.certificat.saml.sp.entity_id }}"
    key_file: "{{ $.Values.certificat.saml.sp.key_file }}"
    cert_file: "{{ $.Values.certificat.saml.sp.cert_file }}"
  {{- if $.Values.certificat.saml.idp.remote_url }}
  idp:
    remote:
      - url: "{{ $.Values.certificat.saml.idp.remote_url }}"
  {{- else }}
  idp:
    mdq:
      - url: "{{ $.Values.certificat.saml.idp.mdq.url }}"
        cert: "{{ $.Values.certificat.saml.idp.mdq.cert }}"
        freshness_period: "{{ $.Values.certificat.saml.idp.mdq.freshness_period }}"
  {{- end }}
{{- end }}

{{- if .Values.sectigo_finalizer }}
{{- $sectigoSecret := lookup "v1" "Secret" .Release.Namespace "certificat-sectigo-secret" }}
{{- $sectigoData := ternary $sectigoSecret.data dict (not $sectigoSecret) }}

sectigo_finalizer:
  org_id: {{ .Values.sectigo_finalizer.org_id }}
  cert_profile_id: {{ .Values.sectigo_finalizer.cert_profile_id }}
  cert_validity_period: {{ .Values.sectigo_finalizer.cert_validity_period }}
  customer_uri: "{{ .Values.sectigo_finalizer.customer_uri }}"
  api_base: "{{ .Values.sectigo_finalizer.api_base }}"
  api_user: "{{ .Values.sectigo_finalizer.api_user | default (get $sectigoData "api_user" | b64dec) }}"
  api_password: "{{ .Values.sectigo_finalizer.api_password | default (get $sectigoData "api_password" | b64dec) }}"
  approval_api_user: "{{ .Values.sectigo_finalizer.approval_api_user | default (get $sectigoData "approval_api_user" | b64dec) }}"
  approval_api_password: "{{ .Values.sectigo_finalizer.approval_api_password | default (get $sectigoData "approval_api_password" | b64dec) }}"
  external_requester_override: "{{ .Values.sectigo_finalizer.external_requester_override }}"
{{- end }}

{{- if or .Values.certificat.local_finalizer.key .Values.certificat.local_finalizer.cert }}
local_finalizer:
  key: |
{{ .Values.certificat.local_finalizer.key | nindent 4 }}
  cert: |
{{ .Values.certificat.local_finalizer.cert | nindent 4 }}
{{- end }}