from dataclasses import dataclass

from certificat.modules.acme import models as db
from .api.schema import (
    generate_order as generate,
    get_certificate as cert,
)
from certificat.settings.dynamic import ApplicationSettings, CertiNextFinalizerSettings
from .api import CertiNextAPIClient
from .api import (
    track_order_schema as track,
)

from certificat.modules.acme.backends import (
    ErrorResponse,
)
import inject
import logging
from certificat import __version__ as certificat_version
from cryptography import x509
from cryptography.x509.oid import NameOID

logger = logging.getLogger(__name__)


@dataclass
class APIResponse:
    status: int
    error: ErrorResponse = None

    def ok(self) -> bool:
        return self.error is None

    def raise_if_not_ok(self):
        if not self.ok():
            code = self.error.code if self.error.code else f"HTTP_{self.status}"
            description = (
                self.error.description
                if self.error.description
                else "No description given"
            )

            raise Exception(f"Error {code}: {description}")


@dataclass
class GenerateOrderResponse(APIResponse):
    order_number: str | None = None


@dataclass
class TrackOrderResponse(APIResponse):
    order_status: int = 1
    order_status_detail: str = None
    certificate_status: int = 1
    certificate_status_detail: str = None


@dataclass
class GetCertificateResponse(APIResponse):
    rootCertificate: str = None
    caCertificate: str = None
    endEntityCertificate: str = None


class CertiNextBackend:
    def generate_order(self, order: db.Order, pem_csr: str) -> GenerateOrderResponse:
        ca_settings: CertiNextFinalizerSettings = inject.instance(
            ApplicationSettings
        ).finalizer

        csr = x509.load_pem_x509_csr(pem_csr.encode())
        try:
            cn = csr.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0].value
        except:  # noqa: E722
            cn = None

        try:
            san_extension = csr.extensions.get_extension_for_class(
                x509.SubjectAlternativeName
            )
            sans = san_extension.value.get_values_for_type(x509.DNSName)
        except x509.extensions.ExtensionNotFound:
            sans = []

        logging.info("CertiNext backend received request to generate new order")

        client = CertiNextAPIClient()
        cert_info = generate.CertificateInformation()
        if cn:
            cert_info.domainName = cn

        if sans:
            cert_info.additionalDomains = sans

        order_details = generate.OrderDetails(
            productCode=ca_settings.product_code,
            requestorInformation=generate.RequestorInformation(
                requestorEmail=ca_settings.requestor_email,
                requestorIsdCode=ca_settings.requestor_isd_code,
                requestorMobileNumber=ca_settings.requestor_mobile_number,
                requestorName=ca_settings.requestor_name,
            ),
            organizationDetails=generate.OrganizationDetails(
                prevettingToken=ca_settings.prevetting_token,
                organizationNumber=ca_settings.prevetted_org_number,
            ),
            certificateInformation=cert_info,
            subscriptionDetails=generate.SubscriptionDetails(),
            csr=pem_csr,
            additionalInformation=generate.AdditionalInformation(
                remarks=f"Generated by CertifiCat v{certificat_version}"
            ),
        )
        req = generate.Request(
            meta=client.generate_meta(),
            orderDetails=order_details,
        )

        try:
            raw_response = client.generate_order(req)
            logger.debug("CertiNext response: %s", raw_response.json())
            response = generate.Response.model_validate(raw_response.json())

            if response.meta.errorCode == "":
                return GenerateOrderResponse(
                    raw_response.status_code,
                    order_number=response.orderDetails.orderNumber,
                )
            else:
                return GenerateOrderResponse(
                    raw_response.status_code,
                    ErrorResponse(
                        response.meta.errorCode,
                        response.meta.errorMessage,
                    ),
                )
        # Could fail because Pydantic fails to validate the model or a generic requests exception
        except Exception as exc:
            return GenerateOrderResponse(
                500, ErrorResponse("E_GEN", "Generic error: " + str(exc))
            )

    def track_order(self, order_number: str) -> TrackOrderResponse:
        logging.info(
            "CertiNext backend received request to track existing order: %s",
            order_number,
        )

        client = CertiNextAPIClient()
        req = track.Request(
            meta=client.generate_meta(),
            orderDetails=track.RequestOrderDetails(orderNumber=order_number),
        )

        try:
            raw_response = client.track_order(req)
            response = track.Response.model_validate(raw_response.json())

            if response.meta.errorCode == "":
                return TrackOrderResponse(
                    raw_response.status_code,
                    order_status=int(response.orderDetails.orderStatusId),
                    order_status_detail=response.orderDetails.orderStatus,
                    certificate_status=int(response.orderDetails.certificateStatusId),
                    certificate_status_detail=response.orderDetails.certificateStatus,
                )
            else:
                return TrackOrderResponse(
                    raw_response.status_code,
                    ErrorResponse(
                        response.meta.errorCode,
                        response.meta.errorMessage,
                    ),
                )

        # Could fail because Pydantic fails to validate the model or a generic requests exception
        except Exception as exc:
            return TrackOrderResponse(
                500, ErrorResponse("E_GEN", "Generic error: " + str(exc))
            )

    def get_certificate(self, order_number: str) -> GetCertificateResponse:
        ca_settings: CertiNextFinalizerSettings = inject.instance(
            ApplicationSettings
        ).finalizer
        logging.info(
            "CertiNext backend received request to get certificate for order: %s",
            order_number,
        )

        client = CertiNextAPIClient()
        req = cert.Request(
            meta=client.generate_meta(),
            orderDetails=cert.RequestOrderDetails(
                orderNumber=order_number, requestorEmail=ca_settings.requestor_email
            ),
        )

        try:
            raw_response = client.get_certificate(req)
            response = cert.Response.model_validate(raw_response.json())

            if response.meta.errorCode == "":
                return GetCertificateResponse(
                    raw_response.status_code,
                    rootCertificate=response.certificateDetails.rootCertificate,
                    caCertificate=response.certificateDetails.caCertificate,
                    endEntityCertificate=response.certificateDetails.endEntityCertificate,
                )
            else:
                return GetCertificateResponse(
                    raw_response.status_code,
                    ErrorResponse(
                        response.meta.errorCode,
                        response.meta.errorMessage,
                    ),
                )
        # Could fail because Pydantic fails to validate the model or a generic requests exception
        except Exception as exc:
            return GetCertificateResponse(
                500, ErrorResponse("E_GEN", "Generic error: " + str(exc))
            )
