# Generated by Django 5.1.2 on 2024-10-15 19:27

import acmev2.models.account
import certificat.modules.acme.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                acmev2.models.account.AccountStatus["valid"],
                                acmev2.models.account.AccountStatus["valid"],
                            ),
                            (
                                acmev2.models.account.AccountStatus["deactivated"],
                                acmev2.models.account.AccountStatus["deactivated"],
                            ),
                            (
                                acmev2.models.account.AccountStatus["revoked"],
                                acmev2.models.account.AccountStatus["revoked"],
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                ("jwk", models.TextField()),
                ("jwk_thumbprint", models.CharField(max_length=100, unique=True)),
            ],
            bases=(models.Model, certificat.modules.acme.models.TimestampMixin),
        ),
    ]
