# Generated by Django 5.1.2 on 2024-11-04 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountbindinggroupscope",
            unique_together={("binding", "group")},
        ),
    ]
