# Generated by Django 5.1.2 on 2024-10-15 19:49

import acmev2.models.identifiers
import acmev2.models.order
import certificat.modules.acme.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, unique=True)),
                ("identifiers", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                acmev2.models.order.OrderStatus["pending"],
                                acmev2.models.order.OrderStatus["pending"],
                            ),
                            (
                                acmev2.models.order.OrderStatus["ready"],
                                acmev2.models.order.OrderStatus["ready"],
                            ),
                            (
                                acmev2.models.order.OrderStatus["processing"],
                                acmev2.models.order.OrderStatus["processing"],
                            ),
                            (
                                acmev2.models.order.OrderStatus["valid"],
                                acmev2.models.order.OrderStatus["valid"],
                            ),
                            (
                                acmev2.models.order.OrderStatus["invalid"],
                                acmev2.models.order.OrderStatus["invalid"],
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                ("expires", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acme.account"
                    ),
                ),
            ],
            bases=(models.Model, certificat.modules.acme.models.TimestampMixin),
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                acmev2.models.identifiers.IdentifierType["dns"],
                                acmev2.models.identifiers.IdentifierType["dns"],
                            )
                        ],
                        max_length=15,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acme.order"
                    ),
                ),
            ],
            bases=(models.Model, certificat.modules.acme.models.TimestampMixin),
        ),
    ]
