# Generated by Django 5.1.2 on 2024-11-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0003_taggedevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="acme.order",
            ),
        ),
        migrations.AlterField(
            model_name="certificaterequest",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate_request",
                to="acme.order",
            ),
        ),
        migrations.AlterField(
            model_name="challengeerror",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="acme.challenge",
            ),
        ),
        migrations.AlterField(
            model_name="orderfinalizationerror",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finalization_errors",
                to="acme.order",
            ),
        ),
    ]
