# Generated by Django 5.1.2 on 2024-10-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0003_remove_order_identifiers_alter_identifier_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="validated",
            field=models.DateTimeField(null=True),
        ),
    ]
