# Generated by Django 5.1.2 on 2024-11-11 16:06

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0004_certificate_metadata_alter_certificate_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="metadata",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
