# Generated by Django 5.1.2 on 2024-10-16 01:46

from django.db import migrations, models
import random
import string


def gen_name():
    return "".join(random.choices(string.ascii_letters + string.digits, k=10))


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0004_challenge_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="name",
            field=models.CharField(default=gen_name, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
