# Generated by Django 5.1.2 on 2024-10-16 01:49

import acmev2.models.challenge
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0005_challenge_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        acmev2.models.challenge.ChallengeStatus["pending"],
                        acmev2.models.challenge.ChallengeStatus["pending"],
                    ),
                    (
                        acmev2.models.challenge.ChallengeStatus["valid"],
                        acmev2.models.challenge.ChallengeStatus["valid"],
                    ),
                    (
                        acmev2.models.challenge.ChallengeStatus["invalid"],
                        acmev2.models.challenge.ChallengeStatus["invalid"],
                    ),
                    (
                        acmev2.models.challenge.ChallengeStatus["processing"],
                        acmev2.models.challenge.ChallengeStatus["processing"],
                    ),
                ],
                default="pending",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
