# Generated by Django 5.1.2 on 2024-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0005_alter_certificate_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempUsageHack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
