# Generated by Django 5.1.2 on 2024-10-16 16:08

import certificat.modules.acme.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0006_challenge_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csr", models.TextField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="acme.order"
                    ),
                ),
            ],
            bases=(models.Model, certificat.modules.acme.models.TimestampMixin),
        ),
    ]
