# Generated by Django 5.1.2 on 2025-02-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0006_tempusagehack"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TempUsageHack",
            new_name="Usage",
        ),
    ]
