# Generated by Django 5.1.2 on 2024-10-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0007_certificaterequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProcessingState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssl_id", models.IntegerField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SU", "Submitted"),
                            ("EN", "Enrolled"),
                            ("AP", "Approved"),
                            ("CO", "Collected"),
                        ],
                        default="SU",
                        max_length=2,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acme.order"
                    ),
                ),
            ],
        ),
    ]
