# Generated by Django 5.2.3 on 2026-06-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0008_termsofservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertinextOrderRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certinext_order_id', models.CharField(max_length=64, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certinext_ref', to='acme.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
