# Generated by Django 5.1.2 on 2024-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acme", "0008_orderprocessingstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderprocessingstate",
            name="ssl_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
