# Generated by Django 5.2.3 on 2025-07-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0008_termsofservice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for the setting",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(blank=True, help_text="Value of the setting"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the setting"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Setting",
                "verbose_name_plural": "Configuration Settings",
                "ordering": ["key"],
            },
        ),
    ]
