# Generated by Django 6.0.3 on 2026-03-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0009_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="EMSignOrderProcessingState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(max_length=50, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SU", "Submitted"),
                            ("OR", "Ordered"),
                            ("FU", "Fulfilled"),
                            ("CO", "Collected"),
                            ("ER", "Errored"),
                        ],
                        default="SU",
                        max_length=2,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acme.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
