# Generated by Django 6.0.3 on 2026-04-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0001_squashed_0010_emsignorderprocessingstate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EMSignOrderProcessingState",
            new_name="CertiNextOrderProcessingState",
        ),
    ]
