# Generated by Django 6.0.3 on 2026-04-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "acme",
            "0011_rename_emsignorderprocessingstate_certinextorderprocessingstate",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ACMEFinalizerBinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("directory", models.URLField()),
                ("account_id", models.URLField()),
                ("key_id", models.CharField(max_length=255)),
                ("private_key", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
