# Generated by Django 6.0.3 on 2026-06-05 14:48

import acmev2.models.challenge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0012_acmefinalizerbinding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        acmev2.models.challenge.ChallengeType["none"],
                        acmev2.models.challenge.ChallengeType["none"],
                    ),
                    (
                        acmev2.models.challenge.ChallengeType["custom"],
                        acmev2.models.challenge.ChallengeType["custom"],
                    ),
                    (
                        acmev2.models.challenge.ChallengeType["dns_01"],
                        acmev2.models.challenge.ChallengeType["dns_01"],
                    ),
                    (
                        acmev2.models.challenge.ChallengeType["http_01"],
                        acmev2.models.challenge.ChallengeType["http_01"],
                    ),
                ],
                max_length=15,
            ),
        ),
    ]
