# Generated by Django 6.0.6 on 2026-06-29 15:15

import acmev2.models.identifiers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0013_alter_challenge_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreAuthorizedAccountIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            (
                                acmev2.models.identifiers.IdentifierType["dns"],
                                acmev2.models.identifiers.IdentifierType["dns"],
                            )
                        ],
                        max_length=15,
                    ),
                ),
                ("identifier_value", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preauthorized_identifiers",
                        to="acme.account",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "identifier_value")},
            },
        ),
    ]
