# Generated by Django 6.0.6 on 2026-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0014_preauthorizedaccountidentifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acmefinalizerbinding",
            name="key_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
