# Generated by Django 6.0.6 on 2026-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme", "0015_alter_acmefinalizerbinding_key_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="finalizer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
