ingress:
  hostname: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: false
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    clawsreg: "true"

imagePullSecrets: 
  - name: gitlab-registry-pull-secret

certificat_image:
  repository: "ghcr.io/rit-its/certificat"
  #repository: "registry.code.rit.edu/its-operations-public/django-acmev2"
  pullPolicy: "Always"

persistentVolumeClaim:
  storageClassName: nfs-client

redis:
  image: "redis:7.2.4"

embedded_mariadb:
  enabled: true
  image: "mariadb:10.5.23-focal"

certificat:
  login_method: "saml"
  saml:
    debug: true
    attribute_mapping:
      eduPersonPrincipalName: username
      mail: email
      givenName: first_name
      sn: last_name

secretProviders:
  samlSp:
    enabled: true
    name: certificat-saml-sp
    type: Opaque
    initialData:
      sp.key: |
        -----BEGIN PRIVATE KEY-----
        GENERATE YOUR OWN!
        -----END PRIVATE KEY-----
      sp.crt: |
        -----BEGIN CERTIFICATE-----
        GENERATE YOUR OWN!
        -----END CERTIFICATE-----

  generated:
    enabled: true
    name: &generatedSecrets 'certificat-env-secret'
    type: 'Generated'
    keys: 
      - django_secret_key
      - mariadb_root_password
      - mariadb_password
      - redis_password

  certificat:
    enabled: true
    name: &certificatSecret 'certificat-file-secret'
    type: 'Opaque'
    initialData:
      certificat.yml: |
        certificat:
          finalizer_module: "certificat.modules.acme.backends.local.LocalFinalizer"
          login_method: "saml"
          db: 
            name: certificat
            user: certificat
            host: mariadb-service.{{ .Release.Namespace }}
          redis:
            host: redis-service.{{ .Release.Namespace }}

        saml:
          debug: false
          attribute_mapping:
            eduPersonPrincipalName: username
            mail: email
            givenName: first_name
            sn: last_name
          sp:
            key_file: "/srv/www/config/sp.key"
            cert_file: "/srv/www/config/sp.crt"
          idp:
            mdq: 
              - url: "http://mdq.incommon.org"
                cert: "/srv/www/config/inc-md-cert-mdq.pem"
                freshness_period: "P0Y0M0DT2H0M0S"

        local_finalizer:
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            GENERATE YOUR OWN!
            -----END RSA PRIVATE KEY-----
          cert: |
            -----BEGIN CERTIFICATE-----
            GENERATE YOUR OWN!
            -----END CERTIFICATE-----

      inc-md-cert-mdq.pem: |
        -----BEGIN CERTIFICATE-----
        [REDACTED FOR BREVITY]
        -----END CERTIFICATE-----

      sp.key: |
        -----BEGIN PRIVATE KEY-----
        GENERATE YOUR OWN!
        -----END PRIVATE KEY-----

      sp.crt: |
        -----BEGIN CERTIFICATE-----
        GENERATE YOUR OWN!
        -----END CERTIFICATE-----

certificat_secrets:
  - from: *generatedSecrets
    mapping:
      CERTIFICAT__SECRET_KEY: django_secret_key
      CERTIFICAT__DB__PASSWORD: mariadb_password
      CERTIFICAT__REDIS__PASSWORD: redis_password

mariadb_secrets:
  - from: *generatedSecrets
    mapping:
      MARIADB_PASSWORD: mariadb_password
      MARIADB_ROOT_PASSWORD: mariadb_root_password

redis_secrets:
  - from: *generatedSecrets
    mapping:
      REDIS_PASSWORD: redis_password