ingress:
  hostname: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: false
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    clawsreg: "true"

imagePullSecrets: 
  - name: gitlab-registry-pull-secret

certificat_image:
  repository: "registry.code.rit.edu/its-operations-public/django-acmev2"
  pullPolicy: "Always"

persistentVolumeClaim:
  storageClassName: nfs-client

redis:
  image: "redis:7.2.4"

embedded_mariadb:
  enabled: true
  image: "mariadb:10.5.23-focal"

certificat:
  login_method: "saml"
  saml:
    debug: true
    attribute_mapping:
      eduPersonPrincipalName: 
        - username
      mail: 
        - email
      givenName: 
        - first_name
      sn: 
        - last_name
    extra_settings:
      want_response_signed: false
      want_assertions_signed: true
    administrators: dmiller.admin@maine.edu, uma.tod.detre@maine.edu,john.warenda.it@maine.edu
    idp:
      remote_url: >-
        https://login.microsoftonline.com/36794658-f219-4ad4-af7b-1b68d1900443/federationmetadata/2007-06/federationmetadata.xml?appid=f1f75c13-57e2-46df-9656-001b2b5a3899
    sp:
      entity_id: https://certificat-sso.k8s-admin.its.maine.edu/saml2/metadata/
      cert: |
        -----BEGIN CERTIFICATE-----
        YOUR SP CERT HERE
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        YOUR SP PRIVATE KEY HERE
        -----END RSA PRIVATE KEY-----

sectigo_finalizer:
  api_base: https://cert-manager.com/api/
  api_user: api@acme.edu
  api_password: password-for-api-user
  approval_api_user: api-approver@acme.edu
  approval_api_password: password-for-api-approver-user
  cert_profile_id: 12345
  cert_validity_period: 90
  customer_uri: InCommon
  external_requester_override: certs@acme.edu
  org_id: 12345

secretProviders:
  generated:
    enabled: true
    name: &generatedSecrets certificat-env-secret
    type: Generated
    keys: 
      - django_secret_key
      - mariadb_root_password
      - mariadb_password
      - redis_password

  certificat:
    enabled: true
    name: &certificatSecret certificat-file-secret
    type: Opaque
    initialData:
      certificat.yml: |-
        {{ tpl (.Files.Get "files/certificat.tpl.yml") . | indent 8 }}
      sp.key: |
        -----BEGIN PRIVATE KEY-----
        YOUR SP PRIVATE KEY HERE
        -----END PRIVATE KEY-----
      sp.crt: |
        -----BEGIN CERTIFICATE-----
        YOUR SP CERT HERE
        -----END CERTIFICATE-----

  sectigo:
    enabled: true
    name: certificat-sectigo-secret
    type: Opaque
    initialData:
      api_user: api@acme.edu
      api_password: password-for-api-user
      approval_api_user: api-approver@acme.edu
      approval_api_password: password-for-api-approver-user

certificat_secrets:
  - from: *generatedSecrets
    mapping:
      CERTIFICAT__SECRET_KEY: django_secret_key
      CERTIFICAT__DB__PASSWORD: mariadb_password
      CERTIFICAT__REDIS__PASSWORD: redis_password

mariadb_secrets:
  - from: *generatedSecrets
    mapping:
      MARIADB_PASSWORD: mariadb_password
      MARIADB_ROOT_PASSWORD: mariadb_root_password

redis_secrets:
  - from: *generatedSecrets
    mapping:
      REDIS_PASSWORD: redis_password