[gitlab-advanced-sast]
  [[gitlab-advanced-sast.ruleset]]
    disable = true
    # Disables template code injection rule, Django auto escapes output.
    [gitlab-advanced-sast.ruleset.identifier]
      type = "semgrep_id"
      value = "bandit.B113"
      
  [[gitlab-advanced-sast.ruleset]]
    disable = true
    # Disables insecure tmp file notice. The hardcoded tmp file created is only 
    # touched, not written to. It's an update marker.
    [gitlab-advanced-sast.ruleset.identifier]
      type = "semgrep_id"
      value = "bandit.B108"
