services:
  certbot:
    links:
      - traefik:certificat.localtest.me
    build:
      context: .
      dockerfile: Dockerfile.certbot
    command: sleep infinity
    ports:
      - "80"
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/dynamic:/etc/traefik/dynamic"
      - "./traefik/certs:/etc/certs"
  app:
    links:
      - certbot:acme.edu
    #  - certbot:subdomain.acme.edu
    #  - certbot:subdommain2.acme.edu
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000"
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      CERTIFICAT__SECRET_KEY: ${_DJ_SECRET_KEY}
      CERTIFICAT__DB__PASSWORD: ${_DJ_MYSQL_ROOT_PWD}
      CERTIFICAT__REDIS__PASSWORD: ${_DJ_REDIS_PWD}
      CERTIFICAT__CONFIG: "/workspaces/certificat/src/certificat_dev/config.yml"
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.certificat.rule=Host(`certificat.localtest.me`)"
      - "traefik.http.routers.certificat.tls=true"
      - "traefik.http.services.certificat.loadbalancer.server.port=8000"

  mariadb:
    image: mariadb:10.5.23-focal
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${_DJ_MYSQL_ROOT_PWD}

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    command: redis-server --save 60 1 --requirepass ${_DJ_REDIS_PWD}

  idp:
    image: kenchan0130/simplesamlphp
    ports: 
      - 8080
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://certificat.localtest.me/saml2/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: https://certificat.localtest.me/saml2/acs/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: https://certificat.localtest.me/saml2/ls/post
    volumes:
      - "../src/certificat_dev/saml/simple_saml_auth.php:/var/www/simplesamlphp/config/authsources.php"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idp.rule=Host(`idp.localtest.me`)"
      - "traefik.http.routers.idp.tls=true"
      - "traefik.http.services.idp.loadbalancer.server.port=8080"

volumes:
  mariadb-data:
