services:
  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    command: sleep infinity
    ports:
      - "80"
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  app:
    links:
      - certbot:acme.edu
      - certbot:subdomain.acme.edu
      - certbot:subdommain2.acme.edu
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000"
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      CERTIFICAT_DB_PASSWORD: ${_DJ_MYSQL_ROOT_PWD}
      CERTIFICAT_DB_NAME: certificat
      CERTIFICAT_DB_USER: root
      CERTIFICAT_DB_HOST: mariadb.
      CERTIFICAT_SECRET_KEY: ${_DJ_SECRET_KEY}
      CERTIFICAT_DEBUG: "True"
      #CERTIFICAT_URL_ROOT: http://localhost:8000
      CERTIFICAT_URL_ROOT: http://certificat.localtest.me
      CERTIFICAT_REDIS_HOST: redis.
      CERTIFICAT_REDIS_PASSWORD: ${_DJ_REDIS_PWD}
      CERTIFICAT_FINALIZER_MODULE: certificat.modules.acme.backends.local.LocalFinalizer
      CERTIFICAT_LOGIN_METHOD: saml
      SAML_DEBUG: True
      SAML_ENTITY_ID: "http://certificat.localtest.me/saml2/metadata/"
      SAML_IDP_METADATA_PATH: "/workspaces/certificat/src/certificat_dev/saml/local-idp.xml"
      SAML_KEY_PATH: "/workspaces/certificat/src/certificat_dev/saml/insecure.key"
      SAML_CERT_PATH: "/workspaces/certificat/src/certificat_dev/saml/insecure.crt"
      LOCAL_CA_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAld0nGypEoP0EKuY1K7PA7auFw94EZy0l2KkbkOcgsdykDcka
        xAa1ST9n5VE96AMTObGWCZb5Fkwv/SPg/RduwcgBLG2y4DjAaR+LafNeRn4Nz7nZ
        85woRr5ojezgy5vzhxti0HqFT5VW1btl0XuPoDoviudJR7vW6koboVRberLJeaA1
        MiRPgxj5tAqlGxMVUEORZhwr5sBgxNNQFXmJzLBCSq2LWHyC75SQJ0AJ3RCNS1V/
        bLtxLj7T7qMji6zbQV3WmF1hQtmKACaCisrxxfg9EEZbTsRRntCOs4NGtRjU9H3n
        zrim9Sj3UjxgydIQ0UKF+DP1dIHbY6XrnowdFQIDAQABAoIBABDQtzYXmIq9yQ1t
        NjMYoMGqOMCg9TqEeNYmJ2crX+JFIQ1A7uVm4Ul+OVCkPH9/dNVI5U5fJ8TGOK49
        K94KFo3cvLD5ABSjmYdSGEkDmyTquO8BagCpGWXSsJWYKiL+dSVIP96nmLS0y4EA
        3WxTYmq2jKYXzIOlgnhYZ2BDQF50bCsjJhTX9+YcOGSkSB5iKPjJFWoj+uvUvKS5
        ar9otrbkNVhVC3PZl4yM3L1C3ubL8ZKPesAaZtGKsZ7Cgd59VVchzjWKrq39vBaU
        4EsxcLtyMlcGsxxPjnGZsj5GoayvAwl/URjslOl237HbpregbwFPdgor/32l0ImB
        Ot3FeIMCgYEAx7qRIgVs4q91SaEazRbV4QhIs7NvpZRq+b5iAOken1wo5xyRJ05q
        X1RFeNolE+pHeooJStemzLy8XSjfGj3e4UygORgca+AMM5xpw/pf3xEHgeQUzxyY
        ZgmXu2nBgBenKwdA+4zAS5Pmm3maI29gKNBN9pmnDpgseuw56d73xu8CgYEAwBYU
        y0kNhwnW80k0bzj9MABDM4FLevYtWb7G9+/ivFxFIghXnaRGajQFVC95rqUR7L0e
        Rphq3EBM7ssNjsLSmFcwEdXLPzOdlpMMxGkNuUIBrN+99mlCBJLMLaWrJh1OlOYt
        C3ErutGyRzYUAdAS8sCn/kexsaBAnyMGaJZC/DsCgYBsGn8TevxEddN11s061HFP
        K7yuByEW7g44vuMsuwDoIGnDLaMjMz4/+szfbLNE5DlsCeqdp7uQdVc+1TBsc7B/
        IYpXXMWFXe88wBw/BvV9NyppE5pvv3p9QBPwTH1/Z04D7BkwDi7GuXbIEDltlIrn
        jFemceQJ8jOhFNsDyrsx4QKBgQC+OyAM0yRagBwohG8xVzcnuprS/1FJTVRMdOuH
        0EK0WIz+z1Q2AuLZevtsDDhuBXxjAEhjkb8CsYt/UgjzQW5fALnSb/EBfpSq8qbK
        PWAiAIS4OD1hM4z2Cou7CT8eWBfizrH9iu7L7bCpZZ0azn51eubkpQwN5a8Z6w4F
        tgpQ0QKBgEiLRI5LxRrzek15RxIRO2QToxBqyXmNAgAPZvDBmQPWPGdF4Vsi16+D
        5KFSdaxo8ZLEDoAKtXbR+9THwRF9PzcvyducZp/dkUFr2x+PZ5yVTjQHwcAVd1Zu
        Wo7xleX2mpTnHQTjtv1NikkMkcIVMz0Y2pbLbhkYyQVG2v6lL4jB
        -----END RSA PRIVATE KEY-----
      LOCAL_CA_CERT: |
        -----BEGIN CERTIFICATE-----
        MIIC1DCCAbygAwIBAgIUQbnQ870aDubvty1Ph5DcCq92JnowDQYJKoZIhvcNAQEL
        BQAwFzEVMBMGA1UEAwwMYWNtZWNhLmxvY2FsMB4XDTI0MTAxNjE5Mzg0MVoXDTM0
        MTAxNDE5Mzg0MVowFzEVMBMGA1UEAwwMYWNtZWNhLmxvY2FsMIIBIjANBgkqhkiG
        9w0BAQEFAAOCAQ8AMIIBCgKCAQEAld0nGypEoP0EKuY1K7PA7auFw94EZy0l2Kkb
        kOcgsdykDckaxAa1ST9n5VE96AMTObGWCZb5Fkwv/SPg/RduwcgBLG2y4DjAaR+L
        afNeRn4Nz7nZ85woRr5ojezgy5vzhxti0HqFT5VW1btl0XuPoDoviudJR7vW6kob
        oVRberLJeaA1MiRPgxj5tAqlGxMVUEORZhwr5sBgxNNQFXmJzLBCSq2LWHyC75SQ
        J0AJ3RCNS1V/bLtxLj7T7qMji6zbQV3WmF1hQtmKACaCisrxxfg9EEZbTsRRntCO
        s4NGtRjU9H3nzrim9Sj3UjxgydIQ0UKF+DP1dIHbY6XrnowdFQIDAQABoxgwFjAU
        BgNVHREEDTALgglsb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEBAE0ZJ8Kl9WzK
        lZFyNyz17fIYGzSej4XKhXk2IajzYaDCKS6pZabHnEuLdxoVqq2SY7Q6tic5vQFY
        20h+btoo/1rC80z328PfewDa98xJwd1v4TcKScBifHRw9KaRRPOHgYaeOeejZp3n
        PjtXes4kQEA6e6sgYFDqbG5RZPKCIbAJUbADPChJocYygrQBmido3tcxNN4PAy8R
        atZhtPs3UzZ4gYJY9wB+MeX5EpLPHQJpoLYQoJO+Q22JuFuPkTfIsQG/Fzvv+hzj
        0aRuPpTug5Kgc1VrD97fjbNVn5Q/v0d8eL+eB7jujTSSXg/iBTH9D/0MSTp0u2Mm
        qIQFqQ2WEBc=
        -----END CERTIFICATE-----  
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.certificat.rule=Host(`certificat.localtest.me`)"
      - "traefik.http.services.certificat.loadbalancer.server.port=8000"

  mariadb:
    image: mariadb:10.5.23-focal
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${_DJ_MYSQL_ROOT_PWD}

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    command: redis-server --save 60 1 --requirepass ${_DJ_REDIS_PWD}

  idp:
    image: kenchan0130/simplesamlphp
    ports:
      - "80"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://certificat.localtest.me/saml2/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://certificat.localtest.me/saml2/acs/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://certificat.localtest.me/saml2/ls/post
    volumes:
      - "../src/certificat_dev/saml/simple_saml_auth.php:/var/www/simplesamlphp/config/authsources.php"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idp.rule=Host(`idp.localtest.me`)"
      - "traefik.http.services.idp.loadbalancer.server.port=8080"

volumes:
  mariadb-data: