#!/usr/bin/env bash

set -euo pipefail

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "${HERE}/shared"

PYPROJECT_FILE="${SRC_PATH}/pyproject.toml"

CURRENT_VERSION="$(tomlq -r ".project.version" "${PYPROJECT_FILE}")"
NEW_VERSION=$(echo "${CURRENT_VERSION%.*}.$((${CURRENT_VERSION##*.}+1))")

read -p "New version, press enter for [${NEW_VERSION}]: " NEW_VERSION_IPT
NEW_VERSION=${NEW_VERSION_IPT:-$NEW_VERSION}

sed -i "s/version = \"${CURRENT_VERSION}\"/version = \"${NEW_VERSION}\"/g" "${PYPROJECT_FILE}"

CHART="${ROOT}/charts/Chart.yaml"
yq -i e ".appVersion |= \"${NEW_VERSION}\"" "${CHART}" &>/dev/null
yq -i e ".version |= \"${NEW_VERSION}\"" "${CHART}" &>/dev/null