#!/usr/bin/env bash

set -euo pipefail

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "${HERE}/shared"

uv pip compile "${SRC_PATH}/pyproject.toml" -o "${SRC_PATH}/requirements.txt" 