#!/usr/bin/env bash

set -euo pipefail

HERE="$(dirname "$(readlink -f "$0")")"

[[ "${1:-}" ]] || {
    echo "Pass the tag"
    exit 1
}

src_image="registry.code.rit.edu/its-operations-public/django-acmev2"
dest_image="ghrc.io/rit-its/certificat"

docker pull "${src_image}:${1}"

docker tag "${src_image}:${1}" "${dest_image}:latest"
docker push "${dest_image}:latest"

docker tag "${src_image}:${1}" "${dest_image}:${1}"
docker push "${dest_image}:${1}"