#!/usr/bin/env bash

set -euo pipefail

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "${HERE}/shared"

run-make setup-venv

"${VENV_PYTHON}" "${LIB_PATH}/manage.py" "${@:1}"