#!/usr/bin/env bash

set -euo pipefail

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "${HERE}/shared"

PYPROJECT_FILE="${SRC_PATH}/pyproject.toml"

echo "Setting version from project file at: ${PYPROJECT_FILE}"

CURRENT_VERSION="$(tomlq -r ".project.version" "${PYPROJECT_FILE}")"
CURRENT_BRANCH="$(git branch --show-current)"

if [ "$CURRENT_BRANCH" == "master" ]; then
    NEW_VERSION="${CURRENT_VERSION}"
else
    NEW_VERSION="${CURRENT_VERSION}-$(echo $CURRENT_BRANCH | tr -cd '[:alnum:]._-').$(date +"%s")"
fi

#NEW_VERSION=$(echo "${CURRENT_VERSION%.*}.$((${CURRENT_VERSION##*.}+1))")

#read -p "New version, press enter for [${NEW_VERSION}]: " NEW_VERSION_IPT
#NEW_VERSION=${NEW_VERSION_IPT:-$NEW_VERSION}

#sed -i "s/version = \"${CURRENT_VERSION}\"/version = \"${NEW_VERSION}\"/g" "${PYPROJECT_FILE}"
echo "New version: $NEW_VERSION"
CHART="${ROOT}/charts/Chart.yaml"

yq -yi ".appVersion |= \"${NEW_VERSION}\"" "${CHART}" &>/dev/null
yq -yi ".version |= \"${NEW_VERSION}\"" "${CHART}" &>/dev/null