#!/usr/bin/env bash

set -euo pipefail

HERE="$(dirname "$(readlink -f "$0")")"
ROOT="$(realpath ${HERE}/../)"
TAG="certificat:test-runner"

docker buildx build \
    -f "${ROOT}/.devcontainer/Dockerfile" . --tag "${TAG}"

CONFIG_FILE="$(mktemp)"
>$CONFIG_FILE
# shellcheck disable=SC2086
chmod 0644 $CONFIG_FILE
    
write-config() {
  DB_TYPE="${DB_TYPE:-mysql}"
  DB_HOST="${DB_HOST:-tmpmariadb.}"
  DB_USER="${DB_USER:-root}"

  cat >"$CONFIG_FILE" <<EOL
certificat:
  secret_key: "12345"
  url_root: "http://localhost:8000"
  
  authentication:
    type: remote
    force_logout_if_no_header: false
    redirect_template: "http://redirect.localhost/?target={ redirect }"

  db:
    type: $DB_TYPE
    name: certificat
    user: $DB_USER
    password: "root"
    host: $DB_HOST
    
  redis:
    host: tmpredis.
    password: "password"

  finalizer:
    type: local
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAld0nGypEoP0EKuY1K7PA7auFw94EZy0l2KkbkOcgsdykDcka
      xAa1ST9n5VE96AMTObGWCZb5Fkwv/SPg/RduwcgBLG2y4DjAaR+LafNeRn4Nz7nZ
      85woRr5ojezgy5vzhxti0HqFT5VW1btl0XuPoDoviudJR7vW6koboVRberLJeaA1
      MiRPgxj5tAqlGxMVUEORZhwr5sBgxNNQFXmJzLBCSq2LWHyC75SQJ0AJ3RCNS1V/
      bLtxLj7T7qMji6zbQV3WmF1hQtmKACaCisrxxfg9EEZbTsRRntCOs4NGtRjU9H3n
      zrim9Sj3UjxgydIQ0UKF+DP1dIHbY6XrnowdFQIDAQABAoIBABDQtzYXmIq9yQ1t
      NjMYoMGqOMCg9TqEeNYmJ2crX+JFIQ1A7uVm4Ul+OVCkPH9/dNVI5U5fJ8TGOK49
      K94KFo3cvLD5ABSjmYdSGEkDmyTquO8BagCpGWXSsJWYKiL+dSVIP96nmLS0y4EA
      3WxTYmq2jKYXzIOlgnhYZ2BDQF50bCsjJhTX9+YcOGSkSB5iKPjJFWoj+uvUvKS5
      ar9otrbkNVhVC3PZl4yM3L1C3ubL8ZKPesAaZtGKsZ7Cgd59VVchzjWKrq39vBaU
      4EsxcLtyMlcGsxxPjnGZsj5GoayvAwl/URjslOl237HbpregbwFPdgor/32l0ImB
      Ot3FeIMCgYEAx7qRIgVs4q91SaEazRbV4QhIs7NvpZRq+b5iAOken1wo5xyRJ05q
      X1RFeNolE+pHeooJStemzLy8XSjfGj3e4UygORgca+AMM5xpw/pf3xEHgeQUzxyY
      ZgmXu2nBgBenKwdA+4zAS5Pmm3maI29gKNBN9pmnDpgseuw56d73xu8CgYEAwBYU
      y0kNhwnW80k0bzj9MABDM4FLevYtWb7G9+/ivFxFIghXnaRGajQFVC95rqUR7L0e
      Rphq3EBM7ssNjsLSmFcwEdXLPzOdlpMMxGkNuUIBrN+99mlCBJLMLaWrJh1OlOYt
      C3ErutGyRzYUAdAS8sCn/kexsaBAnyMGaJZC/DsCgYBsGn8TevxEddN11s061HFP
      K7yuByEW7g44vuMsuwDoIGnDLaMjMz4/+szfbLNE5DlsCeqdp7uQdVc+1TBsc7B/
      IYpXXMWFXe88wBw/BvV9NyppE5pvv3p9QBPwTH1/Z04D7BkwDi7GuXbIEDltlIrn
      jFemceQJ8jOhFNsDyrsx4QKBgQC+OyAM0yRagBwohG8xVzcnuprS/1FJTVRMdOuH
      0EK0WIz+z1Q2AuLZevtsDDhuBXxjAEhjkb8CsYt/UgjzQW5fALnSb/EBfpSq8qbK
      PWAiAIS4OD1hM4z2Cou7CT8eWBfizrH9iu7L7bCpZZ0azn51eubkpQwN5a8Z6w4F
      tgpQ0QKBgEiLRI5LxRrzek15RxIRO2QToxBqyXmNAgAPZvDBmQPWPGdF4Vsi16+D
      5KFSdaxo8ZLEDoAKtXbR+9THwRF9PzcvyducZp/dkUFr2x+PZ5yVTjQHwcAVd1Zu
      Wo7xleX2mpTnHQTjtv1NikkMkcIVMz0Y2pbLbhkYyQVG2v6lL4jB
      -----END RSA PRIVATE KEY-----
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIC1DCCAbygAwIBAgIUQbnQ870aDubvty1Ph5DcCq92JnowDQYJKoZIhvcNAQEL
      BQAwFzEVMBMGA1UEAwwMYWNtZWNhLmxvY2FsMB4XDTI0MTAxNjE5Mzg0MVoXDTM0
      MTAxNDE5Mzg0MVowFzEVMBMGA1UEAwwMYWNtZWNhLmxvY2FsMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAld0nGypEoP0EKuY1K7PA7auFw94EZy0l2Kkb
      kOcgsdykDckaxAa1ST9n5VE96AMTObGWCZb5Fkwv/SPg/RduwcgBLG2y4DjAaR+L
      afNeRn4Nz7nZ85woRr5ojezgy5vzhxti0HqFT5VW1btl0XuPoDoviudJR7vW6kob
      oVRberLJeaA1MiRPgxj5tAqlGxMVUEORZhwr5sBgxNNQFXmJzLBCSq2LWHyC75SQ
      J0AJ3RCNS1V/bLtxLj7T7qMji6zbQV3WmF1hQtmKACaCisrxxfg9EEZbTsRRntCO
      s4NGtRjU9H3nzrim9Sj3UjxgydIQ0UKF+DP1dIHbY6XrnowdFQIDAQABoxgwFjAU
      BgNVHREEDTALgglsb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEBAE0ZJ8Kl9WzK
      lZFyNyz17fIYGzSej4XKhXk2IajzYaDCKS6pZabHnEuLdxoVqq2SY7Q6tic5vQFY
      20h+btoo/1rC80z328PfewDa98xJwd1v4TcKScBifHRw9KaRRPOHgYaeOeejZp3n
      PjtXes4kQEA6e6sgYFDqbG5RZPKCIbAJUbADPChJocYygrQBmido3tcxNN4PAy8R
      atZhtPs3UzZ4gYJY9wB+MeX5EpLPHQJpoLYQoJO+Q22JuFuPkTfIsQG/Fzvv+hzj
      0aRuPpTug5Kgc1VrD97fjbNVn5Q/v0d8eL+eB7jujTSSXg/iBTH9D/0MSTp0u2Mm
      qIQFqQ2WEBc=
      -----END CERTIFICATE-----
EOL
}

docker network create --driver bridge certificat_test &>/dev/null || true

wait-for() {
  local svc="$1"
  local cnt=20
  local out=""
  
  echo -n "Waiting for $1"
  until [ "$cnt" -eq 0 ]; do
    sleep 1
    echo -n "."
    
    set +e
    out="$("${@:2}")"
    if [ "$?" -eq 0 ]; then echo "done" && break; fi
    set -e

    ((cnt--))
  done

  if [ "$cnt" -eq 0 ]; then
    echo -e "timeout.\nLast output: $out"
    exit 1
  fi
}

create-redis-container() {
  local name="tmpredis"
  docker rm -f "$name" &>/dev/null || true
  echo -n "Creating redis container..."
  docker run --name "$name" --network certificat_test -d redis:latest --requirepass password
}

create-mariadb-container() {
  local name="tmpmariadb"
  docker rm -f "$name" &>/dev/null || true
  echo -n "Creating maraidb container..."
  docker run --rm --name "$name" --network certificat_test -d -e MARIADB_DATABASE=certificat -e MARIADB_ROOT_PASSWORD=root mariadb:latest

  wait-for "mariadb container" docker exec -it "$name" mariadb -h localhost -proot --skip-ssl -e "select 'success'"
}

create-postgres-container() {
  local name="tmppostgres"
  docker rm -f "$name" &>/dev/null || true
  echo -n "Creating postgres container..."
  docker run --rm --name "$name" --network certificat_test -d -e POSTGRES_PASSWORD=root postgres

  wait-for "postgres container" docker exec -it $name psql -U postgres -o /tmp/results -Atqc "select 1;"
}

run-tests() {
  docker run --network certificat_test \
    -e CERTIFICAT__CONFIG=/etc/certificat/config.yml \
    --mount "type=bind,source=${CONFIG_FILE},target=/etc/certificat/config.yml" \
    --mount "type=bind,source=${ROOT}/,target=/workspaces/certificat" \
    --user 1000 \
    -it "${TAG}" bash -c '. $HOME/.local/bin/env && /workspaces/certificat/scripts/omnidev test'
}

create-redis-container

create-mariadb-container
DB_TYPE="mysql" DB_HOST="tmpmariadb." write-config
run-tests

create-postgres-container
DB_TYPE="postgresql" DB_HOST="tmppostgres." DB_USER="postgres" write-config
run-tests


