#!/usr/bin/env bash

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ROOT="$(realpath ${HERE}/../)"
SRC_PATH="${ROOT}/src"
LIB_PATH="${SRC_PATH}/certificat"
TESTS_PATH="${LIB_PATH}/tests"
VENV_PATH="${ROOT}/.venv"
VENV_PYTHON="${VENV_PATH}/bin/python3"
ACTIVATE_VENV="${ROOT}/.venv/bin/activate"

run-make() {
    cd "${HERE}"
    make $1
}