#!/usr/bin/env bash

set -euo pipefail

HERE="$(dirname "$(readlink -f "$0")")"
LOGLEVEL='DEBUG'

ROOT="$(realpath ${HERE}/../)"
SRC_PATH="${ROOT}/src"
VENV_PATH="${SRC_PATH}/.venv"
VENV_PYTHON="${VENV_PATH}/bin/python3"
VENV_PYTEST="${VENV_PATH}/bin/pytest"

export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export VIRTUAL_ENV="${VENV_PATH}"

function log_output {
  # shellcheck disable=SC2046
  echo $(date "+%Y/%m/%d %H:%M:%S")" $1"
}

function log_debug {
  if [[ "$LOGLEVEL" =~ ^(DEBUG)$ ]]; then
    log_output "DEBUG $1"
  fi
}

function log_info {
  if [[ "$LOGLEVEL" =~ ^(DEBUG|INFO)$ ]]; then
    log_output "INFO $1"
  fi
}

function log_warn {
  if [[ "$LOGLEVEL" =~ ^(DEBUG|INFO|WARN)$ ]]; then
    log_output "WARN $1"
  fi
}

function log_err {
  if [[ "$LOGLEVEL" =~ ^(DEBUG|INFO|WARN|ERROR)$ ]]; then
    log_output "ERROR $1"
  fi
}

usage() {
  cat <<EOF
Usage: COMMAND [OPTIONS] 

Dev Commands:
  django            Execute Django management command
  start-services    Start all development services
  test              Run pytest
  
Release Commands:
  build             Build distribution files
  bump-version      Automatically bumps and propagates the version 
                    according to the versioning scheme
  gen-bom           Generate software BOM
  gen-tag           Generates a new local tag
EOF
}

[ -z "${1:-}" ] && {
  usage
  exit 1
}

sync_venv() {
  [ ! -d "${VENV_PATH}" ] && { uv venv "${VENV_PATH}"; }
  (
    cd "${SRC_PATH}" &&
      uv sync --python-preference "only-system"
    echo "${SRC_PATH}" >"$(realpath "${VENV_PATH}"/lib/python*)/site-packages/local.pth"
  )
}

start_services() {
  # Start django, huey, and vite
  start_django="${VENV_PYTHON} ${SRC_PATH}/certificat/manage.py runserver"
  start_huey="${VENV_PATH}/bin/watchmedo auto-restart --directory '${SRC_PATH}' --recursiv --patterns *.py -- ${VENV_PYTHON} ${SRC_PATH}/certificat/manage.py run_huey"
  start_vite="cd ${SRC_PATH}/frontend && yarn && yarn dev"

  npx concurrently --handle-input -c "#50C878,#FFF600,#2b3a42" "${start_django}" "${start_huey}" "${start_vite}" --names=django,huey,vite --kill-others
}

manage() {
  "${VENV_PYTHON}" "${SRC_PATH}/certificat/manage.py" "$@"
}

test() {
  (cd "${SRC_PATH}/certificat/tests" && DJANGO_SETTINGS_MODULE="certificat.tests.test_settings" "${VENV_PYTEST}" "$@")
}

gen_bom() {
  uv pip compile "${SRC_PATH}/pyproject.toml" -o "${SRC_PATH}/requirements.txt"
}

build() {
  (
    cd "${SRC_PATH}" &&
      uv build -o "${ROOT}/dist"
  )
}

sync_venv

SUB_COMMAND=${1}
shift
case "$SUB_COMMAND" in
start-services)
  while getopts ":" flag; do
    case "${flag}" in
    *)
      usage
      exit 1
      ;;
    esac
  done

  log_info "Starting all dev services"
  start_services
  ;;

django)
  manage "$@"
  ;;

test)
  test "$@"
  ;;

gen-bom)
  gen_bom "$@"
  ;;

build)
  build "$@"
  ;;

*) usage ;;
esac
