[project]
name = "certificat"
version = "1.0.11"
description = "Web site and reference implementation for the acmev2 package"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = [
    "acmev2==0.1.0",
    "asn1>=2.7.1",
    "django-cotton>=1.3.0",
    "django-csp>=3.8",
    "django-huey>=1.2.1",
    "django-webpack-loader>=3.1.1",
    "django>=5.1.2",
    "djangosaml2>=1.9.3",
    "lxml-html-clean>=0.3.1",
    "mysqlclient>=2.2.4",
    "pydantic-settings>=2.5.2",
    "pyopenssl>=24.2.1",
    "pysaml2>=7.5.0",
    "pyyaml>=6.0.2",
    "redis>=5.1.1",
    "markdown>=3.7",
]

[tool.uv]
dev-dependencies = [
    "acme>=2.11.0",
    "django-debug-toolbar>=4.4.6",
    "dnsmock>=21.2b2",
    "pytest-django>=4.9.0",
    "pytest-mock>=3.14.0",
    "watchdog>=5.0.3",
    "faker>=33.1.0",
    "pytest-cov>=5.0.0",
]


[tool.setuptools.packages.find]
where = ["."]
exclude = ["certificat_dev", "frontend"]

[tool.setuptools.package-data]
"certificat" = ["**/*.html", "**/*.js", "**/*.json", "**/*.ttf", "**/*.woff2", "**/*.css", "**/*.svg", "**/*.ico", "**/*.png"]

