certificat:
  # provided by env
  # secret_key: ""
  debug: True
  url_root: "https://certificat.localtest.me"
  finalizer_module: "certificat.modules.acme.backends.local.LocalFinalizer"
  #finalizer_module: "certificat.modules.acme.backends.sectigo.SectigoFinalizer"
  login_method: "saml"
  trust_proxy_forwarded_proto: True
  db: 
    name: certificat
    user: root
    # provided by env
    # password: ""
    host: mariadb.

  redis:
    host: redis.
    # provided by env
    # password: ""

  logging:
    certificat_level: DEBUG
    acmev2_level: DEBUG

saml:
  debug: True
  administrators:
    - admusr
  attribute_mapping:
    mail: [username, email]
    uid: [username]
    eduPersonPrincipalName: [username]
    givenName: [first_name]
    sn: [last_name]
  #discovery:
  #  service: "https://service.seamlessaccess.org/ds"
  sp:
    entity_id: "http://certificat.localtest.me/saml2/metadata/"
    key_file: "/workspaces/certificat/src/certificat_dev/saml/insecure.key"
    cert_file: "/workspaces/certificat/src/certificat_dev/saml/insecure.crt"
  idp:
    local: 
      - "/workspaces/certificat/src/certificat_dev/saml/local-idp.xml"
    mdq: 
      - url: "https://mdq.incommon.org"
        cert: "/workspaces/certificat/src/certificat_dev/saml/inc-md-cert-mdq.pem"
        freshness_period: "P0Y0M0DT2H0M0S"
        
sectigo_finalizer:
  org_id: 12345
  cert_profile_id: 1234
  customer_uri: InCommon_test
  api_base: https://cert-manager.com/api/
  api_user: user@acme.edu
  api_password: "password"
  approval_api_user: user@acme.edu
  approval_api_password: "password"
  external_requester_override: override@acme.edu
  cert_validity_period: 365

local_finalizer:
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAld0nGypEoP0EKuY1K7PA7auFw94EZy0l2KkbkOcgsdykDcka
    xAa1ST9n5VE96AMTObGWCZb5Fkwv/SPg/RduwcgBLG2y4DjAaR+LafNeRn4Nz7nZ
    85woRr5ojezgy5vzhxti0HqFT5VW1btl0XuPoDoviudJR7vW6koboVRberLJeaA1
    MiRPgxj5tAqlGxMVUEORZhwr5sBgxNNQFXmJzLBCSq2LWHyC75SQJ0AJ3RCNS1V/
    bLtxLj7T7qMji6zbQV3WmF1hQtmKACaCisrxxfg9EEZbTsRRntCOs4NGtRjU9H3n
    zrim9Sj3UjxgydIQ0UKF+DP1dIHbY6XrnowdFQIDAQABAoIBABDQtzYXmIq9yQ1t
    NjMYoMGqOMCg9TqEeNYmJ2crX+JFIQ1A7uVm4Ul+OVCkPH9/dNVI5U5fJ8TGOK49
    K94KFo3cvLD5ABSjmYdSGEkDmyTquO8BagCpGWXSsJWYKiL+dSVIP96nmLS0y4EA
    3WxTYmq2jKYXzIOlgnhYZ2BDQF50bCsjJhTX9+YcOGSkSB5iKPjJFWoj+uvUvKS5
    ar9otrbkNVhVC3PZl4yM3L1C3ubL8ZKPesAaZtGKsZ7Cgd59VVchzjWKrq39vBaU
    4EsxcLtyMlcGsxxPjnGZsj5GoayvAwl/URjslOl237HbpregbwFPdgor/32l0ImB
    Ot3FeIMCgYEAx7qRIgVs4q91SaEazRbV4QhIs7NvpZRq+b5iAOken1wo5xyRJ05q
    X1RFeNolE+pHeooJStemzLy8XSjfGj3e4UygORgca+AMM5xpw/pf3xEHgeQUzxyY
    ZgmXu2nBgBenKwdA+4zAS5Pmm3maI29gKNBN9pmnDpgseuw56d73xu8CgYEAwBYU
    y0kNhwnW80k0bzj9MABDM4FLevYtWb7G9+/ivFxFIghXnaRGajQFVC95rqUR7L0e
    Rphq3EBM7ssNjsLSmFcwEdXLPzOdlpMMxGkNuUIBrN+99mlCBJLMLaWrJh1OlOYt
    C3ErutGyRzYUAdAS8sCn/kexsaBAnyMGaJZC/DsCgYBsGn8TevxEddN11s061HFP
    K7yuByEW7g44vuMsuwDoIGnDLaMjMz4/+szfbLNE5DlsCeqdp7uQdVc+1TBsc7B/
    IYpXXMWFXe88wBw/BvV9NyppE5pvv3p9QBPwTH1/Z04D7BkwDi7GuXbIEDltlIrn
    jFemceQJ8jOhFNsDyrsx4QKBgQC+OyAM0yRagBwohG8xVzcnuprS/1FJTVRMdOuH
    0EK0WIz+z1Q2AuLZevtsDDhuBXxjAEhjkb8CsYt/UgjzQW5fALnSb/EBfpSq8qbK
    PWAiAIS4OD1hM4z2Cou7CT8eWBfizrH9iu7L7bCpZZ0azn51eubkpQwN5a8Z6w4F
    tgpQ0QKBgEiLRI5LxRrzek15RxIRO2QToxBqyXmNAgAPZvDBmQPWPGdF4Vsi16+D
    5KFSdaxo8ZLEDoAKtXbR+9THwRF9PzcvyducZp/dkUFr2x+PZ5yVTjQHwcAVd1Zu
    Wo7xleX2mpTnHQTjtv1NikkMkcIVMz0Y2pbLbhkYyQVG2v6lL4jB
    -----END RSA PRIVATE KEY-----
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIC1DCCAbygAwIBAgIUQbnQ870aDubvty1Ph5DcCq92JnowDQYJKoZIhvcNAQEL
    BQAwFzEVMBMGA1UEAwwMYWNtZWNhLmxvY2FsMB4XDTI0MTAxNjE5Mzg0MVoXDTM0
    MTAxNDE5Mzg0MVowFzEVMBMGA1UEAwwMYWNtZWNhLmxvY2FsMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAld0nGypEoP0EKuY1K7PA7auFw94EZy0l2Kkb
    kOcgsdykDckaxAa1ST9n5VE96AMTObGWCZb5Fkwv/SPg/RduwcgBLG2y4DjAaR+L
    afNeRn4Nz7nZ85woRr5ojezgy5vzhxti0HqFT5VW1btl0XuPoDoviudJR7vW6kob
    oVRberLJeaA1MiRPgxj5tAqlGxMVUEORZhwr5sBgxNNQFXmJzLBCSq2LWHyC75SQ
    J0AJ3RCNS1V/bLtxLj7T7qMji6zbQV3WmF1hQtmKACaCisrxxfg9EEZbTsRRntCO
    s4NGtRjU9H3nzrim9Sj3UjxgydIQ0UKF+DP1dIHbY6XrnowdFQIDAQABoxgwFjAU
    BgNVHREEDTALgglsb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEBAE0ZJ8Kl9WzK
    lZFyNyz17fIYGzSej4XKhXk2IajzYaDCKS6pZabHnEuLdxoVqq2SY7Q6tic5vQFY
    20h+btoo/1rC80z328PfewDa98xJwd1v4TcKScBifHRw9KaRRPOHgYaeOeejZp3n
    PjtXes4kQEA6e6sgYFDqbG5RZPKCIbAJUbADPChJocYygrQBmido3tcxNN4PAy8R
    atZhtPs3UzZ4gYJY9wB+MeX5EpLPHQJpoLYQoJO+Q22JuFuPkTfIsQG/Fzvv+hzj
    0aRuPpTug5Kgc1VrD97fjbNVn5Q/v0d8eL+eB7jujTSSXg/iBTH9D/0MSTp0u2Mm
    qIQFqQ2WEBc=
    -----END CERTIFICATE-----  